import type {
  NewAccount,
  NewBudget,
  NewBudgetItem,
  NewCategory,
  NewRecurringTransaction,
  NewTransaction,
  NewUser,
} from "./types.js";
import { closeDb, db } from "./database.js";
import { runMigrations } from "./migrate.js";

const makeId = (value: number) =>
  `00000000-0000-7000-8000-${value.toString(16).padStart(12, "0")}`;

const months = [1, 2, 3] as const;

const users = {
  trevor: {
    id: "019cf45e-80f5-714a-a121-bb32f8364813",
    name: "Trevor Demo",
    email: "trevor@example.com",
    emailVerified: true,
    image: null,
  },
  jordan: {
    id: makeId(2),
    name: "Jordan Example",
    email: "jordan@example.com",
    emailVerified: true,
    image: null,
  },
} satisfies Record<string, NewUser>;

const allUsers: NewUser[] = Object.values(users);

const categories = {
  trevorPaycheck: {
    id: makeId(101),
    name: "Paycheck",
    group: "Income",
    status: "active",
    userId: users.trevor.id,
  },
  trevorFreelance: {
    id: makeId(102),
    name: "Freelance",
    group: "Income",
    status: "active",
    userId: users.trevor.id,
  },
  trevorHousing: {
    id: makeId(103),
    name: "Housing",
    group: "Bills",
    status: "active",
    userId: users.trevor.id,
  },
  trevorGroceries: {
    id: makeId(104),
    name: "Groceries",
    group: "Food",
    status: "active",
    userId: users.trevor.id,
  },
  trevorDining: {
    id: makeId(105),
    name: "Dining Out",
    group: "Food",
    status: "active",
    userId: users.trevor.id,
  },
  trevorTransportation: {
    id: makeId(106),
    name: "Transportation",
    group: "Transport",
    status: "active",
    userId: users.trevor.id,
  },
  trevorUtilities: {
    id: makeId(107),
    name: "Utilities",
    group: "Bills",
    status: "active",
    userId: users.trevor.id,
  },
  trevorEntertainment: {
    id: makeId(108),
    name: "Entertainment",
    group: "Lifestyle",
    status: "active",
    userId: users.trevor.id,
  },
  trevorHealth: {
    id: makeId(109),
    name: "Health",
    group: "Wellness",
    status: "active",
    userId: users.trevor.id,
  },
  trevorTravel: {
    id: makeId(110),
    name: "Travel",
    group: "Lifestyle",
    status: "active",
    userId: users.trevor.id,
  },
  jordanSalary: {
    id: makeId(201),
    name: "Salary",
    group: "Income",
    status: "active",
    userId: users.jordan.id,
  },
  jordanConsulting: {
    id: makeId(202),
    name: "Consulting",
    group: "Income",
    status: "active",
    userId: users.jordan.id,
  },
  jordanHousing: {
    id: makeId(203),
    name: "Housing",
    group: "Bills",
    status: "active",
    userId: users.jordan.id,
  },
  jordanGroceries: {
    id: makeId(204),
    name: "Groceries",
    group: "Food",
    status: "active",
    userId: users.jordan.id,
  },
  jordanTravel: {
    id: makeId(205),
    name: "Travel",
    group: "Travel",
    status: "active",
    userId: users.jordan.id,
  },
} satisfies Record<string, NewCategory>;

const allCategories: NewCategory[] = Object.values(categories);

const accounts = {
  trevorChecking: {
    id: makeId(301),
    name: "Main Checking",
    type: "checking",
    balance: 5640.12,
    userId: users.trevor.id,
  },
  trevorSavings: {
    id: makeId(302),
    name: "Emergency Savings",
    type: "savings",
    balance: 12840,
    userId: users.trevor.id,
  },
  trevorCredit: {
    id: makeId(303),
    name: "Rewards Credit Card",
    type: "creditCard",
    balance: -612.33,
    userId: users.trevor.id,
  },
  jordanChecking: {
    id: makeId(304),
    name: "Jordan Checking",
    type: "checking",
    balance: 4425.88,
    userId: users.jordan.id,
  },
  jordanTravelCard: {
    id: makeId(305),
    name: "Jordan Travel Card",
    type: "creditCard",
    balance: -340.27,
    userId: users.jordan.id,
  },
} satisfies Record<string, NewAccount>;

const allAccounts: NewAccount[] = Object.values(accounts);

const budgets = {
  trevorJan: { id: makeId(401), month: 1, year: 2026, userId: users.trevor.id },
  trevorFeb: { id: makeId(402), month: 2, year: 2026, userId: users.trevor.id },
  trevorMar: { id: makeId(403), month: 3, year: 2026, userId: users.trevor.id },
  jordanJan: { id: makeId(404), month: 1, year: 2026, userId: users.jordan.id },
  jordanFeb: { id: makeId(405), month: 2, year: 2026, userId: users.jordan.id },
  jordanMar: { id: makeId(406), month: 3, year: 2026, userId: users.jordan.id },
} satisfies Record<string, NewBudget>;

const allBudgets: NewBudget[] = Object.values(budgets);

type BudgetItemSeed = {
  id: string;
  targetAmount: number;
  budgetId: string;
  categoryId: string;
};

const budgetItemSeeds = {
  trevorJanPaycheck: {
    id: makeId(501),
    targetAmount: -5600,
    budgetId: budgets.trevorJan.id,
    categoryId: categories.trevorPaycheck.id,
  },
  trevorJanFreelance: {
    id: makeId(502),
    targetAmount: -650,
    budgetId: budgets.trevorJan.id,
    categoryId: categories.trevorFreelance.id,
  },
  trevorJanHousing: {
    id: makeId(503),
    targetAmount: 1850,
    budgetId: budgets.trevorJan.id,
    categoryId: categories.trevorHousing.id,
  },
  trevorJanGroceries: {
    id: makeId(504),
    targetAmount: 575,
    budgetId: budgets.trevorJan.id,
    categoryId: categories.trevorGroceries.id,
  },
  trevorJanDining: {
    id: makeId(505),
    targetAmount: 230,
    budgetId: budgets.trevorJan.id,
    categoryId: categories.trevorDining.id,
  },
  trevorJanTransportation: {
    id: makeId(506),
    targetAmount: 210,
    budgetId: budgets.trevorJan.id,
    categoryId: categories.trevorTransportation.id,
  },
  trevorJanUtilities: {
    id: makeId(507),
    targetAmount: 260,
    budgetId: budgets.trevorJan.id,
    categoryId: categories.trevorUtilities.id,
  },
  trevorJanEntertainment: {
    id: makeId(508),
    targetAmount: 180,
    budgetId: budgets.trevorJan.id,
    categoryId: categories.trevorEntertainment.id,
  },
  trevorJanHealth: {
    id: makeId(509),
    targetAmount: 120,
    budgetId: budgets.trevorJan.id,
    categoryId: categories.trevorHealth.id,
  },
  trevorFebPaycheck: {
    id: makeId(510),
    targetAmount: -5600,
    budgetId: budgets.trevorFeb.id,
    categoryId: categories.trevorPaycheck.id,
  },
  trevorFebFreelance: {
    id: makeId(511),
    targetAmount: -450,
    budgetId: budgets.trevorFeb.id,
    categoryId: categories.trevorFreelance.id,
  },
  trevorFebHousing: {
    id: makeId(512),
    targetAmount: 1850,
    budgetId: budgets.trevorFeb.id,
    categoryId: categories.trevorHousing.id,
  },
  trevorFebGroceries: {
    id: makeId(513),
    targetAmount: 600,
    budgetId: budgets.trevorFeb.id,
    categoryId: categories.trevorGroceries.id,
  },
  trevorFebDining: {
    id: makeId(514),
    targetAmount: 240,
    budgetId: budgets.trevorFeb.id,
    categoryId: categories.trevorDining.id,
  },
  trevorFebTransportation: {
    id: makeId(515),
    targetAmount: 190,
    budgetId: budgets.trevorFeb.id,
    categoryId: categories.trevorTransportation.id,
  },
  trevorFebUtilities: {
    id: makeId(516),
    targetAmount: 255,
    budgetId: budgets.trevorFeb.id,
    categoryId: categories.trevorUtilities.id,
  },
  trevorFebEntertainment: {
    id: makeId(517),
    targetAmount: 200,
    budgetId: budgets.trevorFeb.id,
    categoryId: categories.trevorEntertainment.id,
  },
  trevorFebTravel: {
    id: makeId(518),
    targetAmount: 300,
    budgetId: budgets.trevorFeb.id,
    categoryId: categories.trevorTravel.id,
  },
  trevorMarPaycheck: {
    id: makeId(519),
    targetAmount: -5600,
    budgetId: budgets.trevorMar.id,
    categoryId: categories.trevorPaycheck.id,
  },
  trevorMarFreelance: {
    id: makeId(520),
    targetAmount: -900,
    budgetId: budgets.trevorMar.id,
    categoryId: categories.trevorFreelance.id,
  },
  trevorMarHousing: {
    id: makeId(521),
    targetAmount: 1850,
    budgetId: budgets.trevorMar.id,
    categoryId: categories.trevorHousing.id,
  },
  trevorMarGroceries: {
    id: makeId(522),
    targetAmount: 625,
    budgetId: budgets.trevorMar.id,
    categoryId: categories.trevorGroceries.id,
  },
  trevorMarDining: {
    id: makeId(523),
    targetAmount: 260,
    budgetId: budgets.trevorMar.id,
    categoryId: categories.trevorDining.id,
  },
  trevorMarTransportation: {
    id: makeId(524),
    targetAmount: 200,
    budgetId: budgets.trevorMar.id,
    categoryId: categories.trevorTransportation.id,
  },
  trevorMarUtilities: {
    id: makeId(525),
    targetAmount: 250,
    budgetId: budgets.trevorMar.id,
    categoryId: categories.trevorUtilities.id,
  },
  trevorMarEntertainment: {
    id: makeId(526),
    targetAmount: 220,
    budgetId: budgets.trevorMar.id,
    categoryId: categories.trevorEntertainment.id,
  },
  trevorMarHealth: {
    id: makeId(527),
    targetAmount: 150,
    budgetId: budgets.trevorMar.id,
    categoryId: categories.trevorHealth.id,
  },
  jordanJanSalary: {
    id: makeId(528),
    targetAmount: -4200,
    budgetId: budgets.jordanJan.id,
    categoryId: categories.jordanSalary.id,
  },
  jordanJanConsulting: {
    id: makeId(529),
    targetAmount: -300,
    budgetId: budgets.jordanJan.id,
    categoryId: categories.jordanConsulting.id,
  },
  jordanJanHousing: {
    id: makeId(530),
    targetAmount: 1650,
    budgetId: budgets.jordanJan.id,
    categoryId: categories.jordanHousing.id,
  },
  jordanJanGroceries: {
    id: makeId(531),
    targetAmount: 420,
    budgetId: budgets.jordanJan.id,
    categoryId: categories.jordanGroceries.id,
  },
  jordanJanTravel: {
    id: makeId(532),
    targetAmount: 260,
    budgetId: budgets.jordanJan.id,
    categoryId: categories.jordanTravel.id,
  },
  jordanFebSalary: {
    id: makeId(533),
    targetAmount: -4200,
    budgetId: budgets.jordanFeb.id,
    categoryId: categories.jordanSalary.id,
  },
  jordanFebConsulting: {
    id: makeId(534),
    targetAmount: -450,
    budgetId: budgets.jordanFeb.id,
    categoryId: categories.jordanConsulting.id,
  },
  jordanFebHousing: {
    id: makeId(535),
    targetAmount: 1650,
    budgetId: budgets.jordanFeb.id,
    categoryId: categories.jordanHousing.id,
  },
  jordanFebGroceries: {
    id: makeId(536),
    targetAmount: 430,
    budgetId: budgets.jordanFeb.id,
    categoryId: categories.jordanGroceries.id,
  },
  jordanFebTravel: {
    id: makeId(537),
    targetAmount: 450,
    budgetId: budgets.jordanFeb.id,
    categoryId: categories.jordanTravel.id,
  },
  jordanMarSalary: {
    id: makeId(538),
    targetAmount: -4200,
    budgetId: budgets.jordanMar.id,
    categoryId: categories.jordanSalary.id,
  },
  jordanMarConsulting: {
    id: makeId(539),
    targetAmount: -350,
    budgetId: budgets.jordanMar.id,
    categoryId: categories.jordanConsulting.id,
  },
  jordanMarHousing: {
    id: makeId(540),
    targetAmount: 1650,
    budgetId: budgets.jordanMar.id,
    categoryId: categories.jordanHousing.id,
  },
  jordanMarGroceries: {
    id: makeId(541),
    targetAmount: 440,
    budgetId: budgets.jordanMar.id,
    categoryId: categories.jordanGroceries.id,
  },
  jordanMarTravel: {
    id: makeId(542),
    targetAmount: 600,
    budgetId: budgets.jordanMar.id,
    categoryId: categories.jordanTravel.id,
  },
} satisfies Record<string, BudgetItemSeed>;

const recurringTransactions = {
  trevorRent: {
    id: makeId(601),
    merchant: "Apartment Management Co",
    amount: 1850,
    notes: "Monthly rent autopay",
    recurringDate: 1,
    userId: users.trevor.id,
    categoryId: categories.trevorHousing.id,
  },
  trevorElectric: {
    id: makeId(602),
    merchant: "City Power",
    amount: 96,
    notes: "Monthly electric bill",
    recurringDate: 8,
    userId: users.trevor.id,
    categoryId: categories.trevorUtilities.id,
  },
  trevorStreaming: {
    id: makeId(603),
    merchant: "StreamBox",
    amount: 18,
    notes: "Streaming subscription",
    recurringDate: 12,
    userId: users.trevor.id,
    categoryId: categories.trevorEntertainment.id,
  },
  jordanSalary: {
    id: makeId(604),
    merchant: "Northwind Labs Payroll",
    amount: 4200,
    notes: "Monthly salary",
    recurringDate: 1,
    userId: users.jordan.id,
    categoryId: categories.jordanSalary.id,
  },
  jordanRent: {
    id: makeId(605),
    merchant: "Maple Street Apartments",
    amount: 1650,
    notes: "Monthly rent",
    recurringDate: 2,
    userId: users.jordan.id,
    categoryId: categories.jordanHousing.id,
  },
} satisfies Record<string, NewRecurringTransaction>;

const allRecurringTransactions: NewRecurringTransaction[] = Object.values(recurringTransactions);

const transactions: NewTransaction[] = [
  {
    id: makeId(701),
    merchant: "Acme Corp Payroll",
    amount: 2800,
    notes: "January paycheck",
    type: "credit",
    date: "2026-01-01T14:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorChecking.id,
    budgetItemId: budgetItemSeeds.trevorJanPaycheck.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(702),
    merchant: "Acme Corp Payroll",
    amount: 2800,
    notes: "Second January paycheck",
    type: "credit",
    date: "2026-01-15T14:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorChecking.id,
    budgetItemId: budgetItemSeeds.trevorJanPaycheck.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(703),
    merchant: "Brightside Studio",
    amount: 720,
    notes: "Website sprint invoice",
    type: "credit",
    date: "2026-01-21T19:30:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorChecking.id,
    budgetItemId: budgetItemSeeds.trevorJanFreelance.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(704),
    merchant: "Apartment Management Co",
    amount: 1850,
    notes: "January rent",
    type: "debit",
    date: "2026-01-02T15:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorChecking.id,
    budgetItemId: budgetItemSeeds.trevorJanHousing.id,
    recurringTemplateId: recurringTransactions.trevorRent.id,
  },
  {
    id: makeId(705),
    merchant: "Fresh Market",
    amount: 136.42,
    notes: "Week 1 groceries",
    type: "debit",
    date: "2026-01-05T18:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorChecking.id,
    budgetItemId: budgetItemSeeds.trevorJanGroceries.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(706),
    merchant: "Trader Joe's",
    amount: 118.67,
    notes: "Week 2 groceries",
    type: "debit",
    date: "2026-01-12T18:30:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorChecking.id,
    budgetItemId: budgetItemSeeds.trevorJanGroceries.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(707),
    merchant: "Costco",
    amount: 154.1,
    notes: "Bulk household restock",
    type: "debit",
    date: "2026-01-24T20:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorCredit.id,
    budgetItemId: budgetItemSeeds.trevorJanGroceries.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(708),
    merchant: "Neighborhood Cafe",
    amount: 22.4,
    notes: "Lunch with coworker",
    type: "debit",
    date: "2026-01-09T19:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorCredit.id,
    budgetItemId: budgetItemSeeds.trevorJanDining.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(709),
    merchant: "Sushi House",
    amount: 48.25,
    notes: "Friday dinner",
    type: "debit",
    date: "2026-01-23T23:15:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorCredit.id,
    budgetItemId: budgetItemSeeds.trevorJanDining.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(710),
    merchant: "Metro Transit",
    amount: 45,
    notes: "Monthly pass reload",
    type: "debit",
    date: "2026-01-03T13:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorChecking.id,
    budgetItemId: budgetItemSeeds.trevorJanTransportation.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(711),
    merchant: "Shell",
    amount: 39.84,
    notes: "Gas fill-up",
    type: "debit",
    date: "2026-01-18T16:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorCredit.id,
    budgetItemId: budgetItemSeeds.trevorJanTransportation.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(712),
    merchant: "City Power",
    amount: 94.2,
    notes: "Electric bill",
    type: "debit",
    date: "2026-01-08T14:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorChecking.id,
    budgetItemId: budgetItemSeeds.trevorJanUtilities.id,
    recurringTemplateId: recurringTransactions.trevorElectric.id,
  },
  {
    id: makeId(713),
    merchant: "FiberFast",
    amount: 68,
    notes: "Internet service",
    type: "debit",
    date: "2026-01-10T15:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorChecking.id,
    budgetItemId: budgetItemSeeds.trevorJanUtilities.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(714),
    merchant: "StreamBox",
    amount: 18,
    notes: "Monthly streaming",
    type: "debit",
    date: "2026-01-12T08:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorCredit.id,
    budgetItemId: budgetItemSeeds.trevorJanEntertainment.id,
    recurringTemplateId: recurringTransactions.trevorStreaming.id,
  },
  {
    id: makeId(715),
    merchant: "Music Hall",
    amount: 62.5,
    notes: "Concert tickets",
    type: "debit",
    date: "2026-01-27T02:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorCredit.id,
    budgetItemId: budgetItemSeeds.trevorJanEntertainment.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(716),
    merchant: "Lakeview Clinic",
    amount: 35,
    notes: "Copay",
    type: "debit",
    date: "2026-01-19T17:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorChecking.id,
    budgetItemId: budgetItemSeeds.trevorJanHealth.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(717),
    merchant: "Acme Corp Payroll",
    amount: 2800,
    notes: "February paycheck",
    type: "credit",
    date: "2026-02-01T14:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorChecking.id,
    budgetItemId: budgetItemSeeds.trevorFebPaycheck.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(718),
    merchant: "Acme Corp Payroll",
    amount: 2800,
    notes: "Second February paycheck",
    type: "credit",
    date: "2026-02-15T14:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorChecking.id,
    budgetItemId: budgetItemSeeds.trevorFebPaycheck.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(719),
    merchant: "Freelance Collective",
    amount: 420,
    notes: "Branding workshop",
    type: "credit",
    date: "2026-02-11T20:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorChecking.id,
    budgetItemId: budgetItemSeeds.trevorFebFreelance.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(720),
    merchant: "Apartment Management Co",
    amount: 1850,
    notes: "February rent",
    type: "debit",
    date: "2026-02-02T15:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorChecking.id,
    budgetItemId: budgetItemSeeds.trevorFebHousing.id,
    recurringTemplateId: recurringTransactions.trevorRent.id,
  },
  {
    id: makeId(721),
    merchant: "Whole Foods",
    amount: 144.33,
    notes: "Weekly groceries",
    type: "debit",
    date: "2026-02-06T18:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorChecking.id,
    budgetItemId: budgetItemSeeds.trevorFebGroceries.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(722),
    merchant: "Trader Joe's",
    amount: 132.9,
    notes: "Weekly groceries",
    type: "debit",
    date: "2026-02-14T18:30:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorChecking.id,
    budgetItemId: budgetItemSeeds.trevorFebGroceries.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(723),
    merchant: "Costco",
    amount: 168.74,
    notes: "Household restock",
    type: "debit",
    date: "2026-02-22T19:30:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorCredit.id,
    budgetItemId: budgetItemSeeds.trevorFebGroceries.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(724),
    merchant: "Thai Garden",
    amount: 34.22,
    notes: "Dinner out",
    type: "debit",
    date: "2026-02-07T23:30:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorCredit.id,
    budgetItemId: budgetItemSeeds.trevorFebDining.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(725),
    merchant: "Wine & Cheese",
    amount: 58.4,
    notes: "Date night",
    type: "debit",
    date: "2026-02-21T23:45:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorCredit.id,
    budgetItemId: budgetItemSeeds.trevorFebDining.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(726),
    merchant: "Metro Transit",
    amount: 45,
    notes: "Monthly pass reload",
    type: "debit",
    date: "2026-02-03T13:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorChecking.id,
    budgetItemId: budgetItemSeeds.trevorFebTransportation.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(727),
    merchant: "Shell",
    amount: 51.11,
    notes: "Gas fill-up",
    type: "debit",
    date: "2026-02-16T16:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorCredit.id,
    budgetItemId: budgetItemSeeds.trevorFebTransportation.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(728),
    merchant: "City Power",
    amount: 101.4,
    notes: "Electric bill",
    type: "debit",
    date: "2026-02-08T14:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorChecking.id,
    budgetItemId: budgetItemSeeds.trevorFebUtilities.id,
    recurringTemplateId: recurringTransactions.trevorElectric.id,
  },
  {
    id: makeId(729),
    merchant: "FiberFast",
    amount: 68,
    notes: "Internet service",
    type: "debit",
    date: "2026-02-10T15:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorChecking.id,
    budgetItemId: budgetItemSeeds.trevorFebUtilities.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(730),
    merchant: "StreamBox",
    amount: 18,
    notes: "Monthly streaming",
    type: "debit",
    date: "2026-02-12T08:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorCredit.id,
    budgetItemId: budgetItemSeeds.trevorFebEntertainment.id,
    recurringTemplateId: recurringTransactions.trevorStreaming.id,
  },
  {
    id: makeId(731),
    merchant: "Cinema 8",
    amount: 41,
    notes: "Movie night",
    type: "debit",
    date: "2026-02-20T02:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorCredit.id,
    budgetItemId: budgetItemSeeds.trevorFebEntertainment.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(732),
    merchant: "Midwest Air",
    amount: 220,
    notes: "Conference flight deposit",
    type: "debit",
    date: "2026-02-25T17:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorCredit.id,
    budgetItemId: budgetItemSeeds.trevorFebTravel.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(733),
    merchant: "Acme Corp Payroll",
    amount: 2800,
    notes: "March paycheck",
    type: "credit",
    date: "2026-03-01T14:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorChecking.id,
    budgetItemId: budgetItemSeeds.trevorMarPaycheck.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(734),
    merchant: "Acme Corp Payroll",
    amount: 2800,
    notes: "Second March paycheck",
    type: "credit",
    date: "2026-03-15T14:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorChecking.id,
    budgetItemId: budgetItemSeeds.trevorMarPaycheck.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(735),
    merchant: "Brightside Studio",
    amount: 920,
    notes: "Quarterly design sprint",
    type: "credit",
    date: "2026-03-06T20:30:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorChecking.id,
    budgetItemId: budgetItemSeeds.trevorMarFreelance.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(736),
    merchant: "Apartment Management Co",
    amount: 1850,
    notes: "March rent",
    type: "debit",
    date: "2026-03-02T15:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorChecking.id,
    budgetItemId: budgetItemSeeds.trevorMarHousing.id,
    recurringTemplateId: recurringTransactions.trevorRent.id,
  },
  {
    id: makeId(737),
    merchant: "Whole Foods",
    amount: 148.2,
    notes: "Weekly groceries",
    type: "debit",
    date: "2026-03-05T18:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorChecking.id,
    budgetItemId: budgetItemSeeds.trevorMarGroceries.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(738),
    merchant: "Trader Joe's",
    amount: 134.12,
    notes: "Weekly groceries",
    type: "debit",
    date: "2026-03-13T18:30:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorChecking.id,
    budgetItemId: budgetItemSeeds.trevorMarGroceries.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(739),
    merchant: "Costco",
    amount: 179.88,
    notes: "Household restock",
    type: "debit",
    date: "2026-03-22T19:30:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorCredit.id,
    budgetItemId: budgetItemSeeds.trevorMarGroceries.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(740),
    merchant: "Neighborhood Cafe",
    amount: 29.5,
    notes: "Lunch with friend",
    type: "debit",
    date: "2026-03-09T19:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorCredit.id,
    budgetItemId: budgetItemSeeds.trevorMarDining.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(741),
    merchant: "Sushi House",
    amount: 64.9,
    notes: "Birthday dinner",
    type: "debit",
    date: "2026-03-28T23:15:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorCredit.id,
    budgetItemId: budgetItemSeeds.trevorMarDining.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(742),
    merchant: "Metro Transit",
    amount: 45,
    notes: "Monthly pass reload",
    type: "debit",
    date: "2026-03-03T13:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorChecking.id,
    budgetItemId: budgetItemSeeds.trevorMarTransportation.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(743),
    merchant: "Shell",
    amount: 44.67,
    notes: "Gas fill-up",
    type: "debit",
    date: "2026-03-18T16:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorCredit.id,
    budgetItemId: budgetItemSeeds.trevorMarTransportation.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(744),
    merchant: "City Power",
    amount: 98.76,
    notes: "Electric bill",
    type: "debit",
    date: "2026-03-08T14:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorChecking.id,
    budgetItemId: budgetItemSeeds.trevorMarUtilities.id,
    recurringTemplateId: recurringTransactions.trevorElectric.id,
  },
  {
    id: makeId(745),
    merchant: "FiberFast",
    amount: 68,
    notes: "Internet service",
    type: "debit",
    date: "2026-03-10T15:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorChecking.id,
    budgetItemId: budgetItemSeeds.trevorMarUtilities.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(746),
    merchant: "StreamBox",
    amount: 18,
    notes: "Monthly streaming",
    type: "debit",
    date: "2026-03-12T08:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorCredit.id,
    budgetItemId: budgetItemSeeds.trevorMarEntertainment.id,
    recurringTemplateId: recurringTransactions.trevorStreaming.id,
  },
  {
    id: makeId(747),
    merchant: "Arcade Social",
    amount: 52.25,
    notes: "Weekend with friends",
    type: "debit",
    date: "2026-03-26T02:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorCredit.id,
    budgetItemId: budgetItemSeeds.trevorMarEntertainment.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(748),
    merchant: "Lakeview Clinic",
    amount: 48,
    notes: "Physical therapy copay",
    type: "debit",
    date: "2026-03-17T17:00:00.000Z",
    userId: users.trevor.id,
    accountId: accounts.trevorChecking.id,
    budgetItemId: budgetItemSeeds.trevorMarHealth.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(749),
    merchant: "Northwind Labs Payroll",
    amount: 4200,
    notes: "January salary",
    type: "credit",
    date: "2026-01-01T12:00:00.000Z",
    userId: users.jordan.id,
    accountId: accounts.jordanChecking.id,
    budgetItemId: budgetItemSeeds.jordanJanSalary.id,
    recurringTemplateId: recurringTransactions.jordanSalary.id,
  },
  {
    id: makeId(750),
    merchant: "Jordan Consulting LLC",
    amount: 325,
    notes: "January consulting",
    type: "credit",
    date: "2026-01-20T18:00:00.000Z",
    userId: users.jordan.id,
    accountId: accounts.jordanChecking.id,
    budgetItemId: budgetItemSeeds.jordanJanConsulting.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(751),
    merchant: "Maple Street Apartments",
    amount: 1650,
    notes: "January rent",
    type: "debit",
    date: "2026-01-02T15:00:00.000Z",
    userId: users.jordan.id,
    accountId: accounts.jordanChecking.id,
    budgetItemId: budgetItemSeeds.jordanJanHousing.id,
    recurringTemplateId: recurringTransactions.jordanRent.id,
  },
  {
    id: makeId(752),
    merchant: "Local Market",
    amount: 118.22,
    notes: "January groceries",
    type: "debit",
    date: "2026-01-08T19:00:00.000Z",
    userId: users.jordan.id,
    accountId: accounts.jordanChecking.id,
    budgetItemId: budgetItemSeeds.jordanJanGroceries.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(753),
    merchant: "Fresh Mart",
    amount: 126.11,
    notes: "January groceries restock",
    type: "debit",
    date: "2026-01-22T19:00:00.000Z",
    userId: users.jordan.id,
    accountId: accounts.jordanChecking.id,
    budgetItemId: budgetItemSeeds.jordanJanGroceries.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(754),
    merchant: "Amtrak",
    amount: 140,
    notes: "January train to Chicago",
    type: "debit",
    date: "2026-01-25T16:30:00.000Z",
    userId: users.jordan.id,
    accountId: accounts.jordanTravelCard.id,
    budgetItemId: budgetItemSeeds.jordanJanTravel.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(755),
    merchant: "Northwind Labs Payroll",
    amount: 4200,
    notes: "February salary",
    type: "credit",
    date: "2026-02-01T12:00:00.000Z",
    userId: users.jordan.id,
    accountId: accounts.jordanChecking.id,
    budgetItemId: budgetItemSeeds.jordanFebSalary.id,
    recurringTemplateId: recurringTransactions.jordanSalary.id,
  },
  {
    id: makeId(756),
    merchant: "Jordan Consulting LLC",
    amount: 480,
    notes: "February consulting",
    type: "credit",
    date: "2026-02-14T18:00:00.000Z",
    userId: users.jordan.id,
    accountId: accounts.jordanChecking.id,
    budgetItemId: budgetItemSeeds.jordanFebConsulting.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(757),
    merchant: "Maple Street Apartments",
    amount: 1650,
    notes: "February rent",
    type: "debit",
    date: "2026-02-02T15:00:00.000Z",
    userId: users.jordan.id,
    accountId: accounts.jordanChecking.id,
    budgetItemId: budgetItemSeeds.jordanFebHousing.id,
    recurringTemplateId: recurringTransactions.jordanRent.id,
  },
  {
    id: makeId(758),
    merchant: "Local Market",
    amount: 134.57,
    notes: "February groceries",
    type: "debit",
    date: "2026-02-07T19:00:00.000Z",
    userId: users.jordan.id,
    accountId: accounts.jordanChecking.id,
    budgetItemId: budgetItemSeeds.jordanFebGroceries.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(759),
    merchant: "Fresh Mart",
    amount: 118.09,
    notes: "February groceries restock",
    type: "debit",
    date: "2026-02-21T19:00:00.000Z",
    userId: users.jordan.id,
    accountId: accounts.jordanChecking.id,
    budgetItemId: budgetItemSeeds.jordanFebGroceries.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(760),
    merchant: "Skyline Air",
    amount: 210,
    notes: "Conference flight",
    type: "debit",
    date: "2026-02-24T18:30:00.000Z",
    userId: users.jordan.id,
    accountId: accounts.jordanTravelCard.id,
    budgetItemId: budgetItemSeeds.jordanFebTravel.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(761),
    merchant: "Northwind Labs Payroll",
    amount: 4200,
    notes: "March salary",
    type: "credit",
    date: "2026-03-01T12:00:00.000Z",
    userId: users.jordan.id,
    accountId: accounts.jordanChecking.id,
    budgetItemId: budgetItemSeeds.jordanMarSalary.id,
    recurringTemplateId: recurringTransactions.jordanSalary.id,
  },
  {
    id: makeId(762),
    merchant: "Jordan Consulting LLC",
    amount: 390,
    notes: "March consulting",
    type: "credit",
    date: "2026-03-18T18:00:00.000Z",
    userId: users.jordan.id,
    accountId: accounts.jordanChecking.id,
    budgetItemId: budgetItemSeeds.jordanMarConsulting.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(763),
    merchant: "Maple Street Apartments",
    amount: 1650,
    notes: "March rent",
    type: "debit",
    date: "2026-03-02T15:00:00.000Z",
    userId: users.jordan.id,
    accountId: accounts.jordanChecking.id,
    budgetItemId: budgetItemSeeds.jordanMarHousing.id,
    recurringTemplateId: recurringTransactions.jordanRent.id,
  },
  {
    id: makeId(764),
    merchant: "Local Market",
    amount: 142.73,
    notes: "March groceries",
    type: "debit",
    date: "2026-03-07T19:00:00.000Z",
    userId: users.jordan.id,
    accountId: accounts.jordanChecking.id,
    budgetItemId: budgetItemSeeds.jordanMarGroceries.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(765),
    merchant: "Fresh Mart",
    amount: 129.84,
    notes: "March groceries restock",
    type: "debit",
    date: "2026-03-23T19:00:00.000Z",
    userId: users.jordan.id,
    accountId: accounts.jordanChecking.id,
    budgetItemId: budgetItemSeeds.jordanMarGroceries.id,
    recurringTemplateId: null,
  },
  {
    id: makeId(766),
    merchant: "Oceanview Hotel",
    amount: 255,
    notes: "Spring trip hotel deposit",
    type: "debit",
    date: "2026-03-20T18:30:00.000Z",
    userId: users.jordan.id,
    accountId: accounts.jordanTravelCard.id,
    budgetItemId: budgetItemSeeds.jordanMarTravel.id,
    recurringTemplateId: null,
  },
];

const signedAmount = (transaction: Pick<NewTransaction, "amount" | "type">) => {
  return transaction.type === "debit" ? transaction.amount : -transaction.amount;
};

const budgetItems: NewBudgetItem[] = Object.values(budgetItemSeeds).map((seed) => ({
  id: seed.id,
  targetAmount: seed.targetAmount,
  actualAmount: transactions
    .filter((transaction) => transaction.budgetItemId === seed.id)
    .reduce((sum, transaction) => sum + signedAmount(transaction), 0),
  budgetId: seed.budgetId,
  categoryId: seed.categoryId,
}));

const resetTables = async () => {
  await db.deleteFrom("transactions").execute();
  await db.deleteFrom("recurringTransaction").execute();
  await db.deleteFrom("budgetItems").execute();
  await db.deleteFrom("budgets").execute();
  await db.deleteFrom("accounts").execute();
  await db.deleteFrom("categories").execute();
  await db.deleteFrom("authSessions").execute();
  await db.deleteFrom("authAccounts").execute();
  await db.deleteFrom("authVerifications").execute();
  await db.deleteFrom("users").execute();
};

const seed = async () => {
  try {
    await runMigrations();
    await resetTables();

    await db.insertInto("users").values(allUsers).execute();
    await db.insertInto("categories").values(allCategories).execute();
    await db.insertInto("accounts").values(allAccounts).execute();
    await db.insertInto("budgets").values(allBudgets).execute();
    await db.insertInto("budgetItems").values(budgetItems).execute();
    await db
      .insertInto("recurringTransaction")
      .values(allRecurringTransactions)
      .execute();
    await db.insertInto("transactions").values(transactions).execute();

    console.log(
      `Seed completed successfully with ${allUsers.length} users, ${allBudgets.length} budgets, ${budgetItems.length} budget items, ${allRecurringTransactions.length} recurring transactions, and ${transactions.length} transactions across January-March 2026.`,
    );
  } finally {
    await closeDb();
  }
};

void seed();
